services:
  mosquitto:
    build:
      context: .
      dockerfile: Dockerfile.mqtt
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    stdin_open: true
    tty: true

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: rfid
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

#  cloudbeaver:
#      image: dbeaver/cloudbeaver
#      ports:
#       - '8080:8978'
#      volumes:
#       - cloudbeaver_data:/opt/cloudbeaver/workspace

volumes:
  mosquitto_data:
    driver: local
  mosquitto_log:
    driver: local
  mariadb_data:
    driver: local
#  cloudbeaver_data:
#    driver: local
