services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    stdin_open: true
    tty: true
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: rfid
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql

#  cloudbeaver:
#      image: dbeaver/cloudbeaver
#      ports:
#       - '8080:8978'
#      volumes:
#       - ./cloudbeaver:/opt/cloudbeaver/workspace